# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: ðŸš€ [TypeScript] release

on:
  push:
    branches:
    - typescript

jobs:
    release:
        name: ðŸš€ [TypeScript] release
        runs-on: ubuntu-latest
        steps:
            - name: ðŸ“š [TypeScript] checkout
              uses: actions/checkout@v3
            - name: ðŸŸ¢ [TypeScript]  node
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  registry-url: https://registry.npmjs.org
            - name: ðŸš€ [TypeScript] publish
              run: npm publish --tag typescript --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}